In [1]:
import pandas as pd
input_path="/Users/dongjian/data/ad_feedback.csv"

In [2]:
inp = pd.read_csv(input_path)

In [5]:
inp.columns = ["id", "reorder_ratio", "dedup_reorder_ratio", "reorder_count",
               "total", "dedup_reorder_count", "dedup_total", "dt", "ratio"]

In [7]:
inp[inp.dt<=20171212]

,id,reorder_ratio,dedup_reorder_ratio,reorder_count,total,dedup_reorder_count,dedup_total,dt,ratio
0,1801,0.056827,0.056360,673,11843,662,11746,20171206,-0.002374
1,1802,0.055452,0.054993,656,11830,646,11747,20171206,-0.026505
2,1803,0.056962,0.056463,675,11850,664,11760,20171206,0.000000
3,1804,0.059320,0.058754,703,11851,691,11761,20171206,0.041394
4,1805,0.065915,0.064894,766,11621,747,11511,20171206,0.157177
5,1801,0.055676,0.055689,514,9232,510,9158,20171207,0.059195
6,1802,0.055806,0.055519,519,9300,513,9240,20171207,0.061678
7,1803,0.052564,0.052232,494,9398,488,9343,20171207,0.000000
8,1804,0.058264,0.057538,539,9251,529,9194,20171207,0.108431
9,1805,0.053974,0.054066,508,9412,506,9359,20171207,0.026810
10,1801,0.052191,0.051887,623,11937,616,11872,20171208,-0.029496
11,1802,0.053332,0.052412,645,12094,629,12001,20171208,-0.008269
12,1803,0.053777,0.053074,645,11994,632,11908,20171208,0.000000
13,1804,0.050025,0.049345,597,11934,584,11835,20171208,-0.069765
14,1805,0.050471,0.049775,611,12106,598,12014,20171208,-0.061477
15,1801,0.050064,0.049517,664,13263,651,13147,20171209,0.052209
16,1802,0.044657,0.044274,588,13167,578,13055,20171209,-0.061431
17,1803,0.047580,0.047207,638,13409,628,13303,20171209,0.000000
18,1804,0.044642,0.044120,597,13373,586,13282,20171209,-0.061744
19,1805,0.047300,0.046616,650,13742,635,13622,20171209,-0.005879
20,1801,0.046727,0.046136,616,13183,603,13070,20171210,-0.000833
21,1802,0.047212,0.046410,618,13090,603,12993,20171210,0.009533
22,1803,0.046766,0.045979,629,13450,614,13354,20171210,0.000000
23,1804,0.046144,0.045704,618,13393,607,13281,20171210,-0.013307
24,1805,0.050423,0.049314,667,13228,647,13120,20171210,0.078210
25,1801,0.041878,0.041480,480,11462,472,11379,20171211,-0.103647
26,1802,0.043593,0.042999,494,11332,484,11256,20171211,-0.066920
27,1803,0.046720,0.046117,527,11280,516,11189,20171211,0.000000
28,1804,0.045511,0.045090,515,11316,506,11222,20171211,-0.025879
29,1805,0.045406,0.043653,512,11276,488,11179,20171211,-0.028118
30,1801,0.039188,0.038512,448,11432,437,11347,20171212,-0.046168
31,1802,0.038878,0.038627,445,11446,439,11365,20171212,-0.053714
32,1803,0.041085,0.040948,468,11391,463,11307,20171212,0.000000
33,1804,0.037729,0.037503,432,11450,426,11359,20171212,-0.081680
34,1805,0.038312,0.037195,442,11537,426,11453,20171212,-0.067507

In [54]:
rs = inp[inp.dt<=20171208].groupby("id").agg({"dedup_reorder_count":"sum","dedup_total":"sum"})
rs['ratio'] = rs["dedup_reorder_count"]/rs["dedup_total"]
rs

,dedup_total,dedup_reorder_count,ratio
id,,,
1801,32776,1788,0.054552
1802,32988,1788,0.054202
1803,33011,1784,0.054043
1804,32790,1804,0.055017
1805,32884,1851,0.056289

In [25]:
a = rs.unstack().unstack()

In [45]:
a[]

id,1801,1802,1803,1804,1805
dedup_total,81719.000000,81657.000000,82164.000000,81934.000000,82258.000000
dedup_reorder_count,3951.000000,3892.000000,4005.000000,3929.000000,4047.000000
ratio,0.048349,0.047663,0.048744,0.047953,0.049199

In [47]:
(0.056289 - 0.054552)/0.054043

0.03214107284939762